#!/bin/sh
# git-create-branch <source_branch> <branch_name>
 
if [ $# -ne 2 ]; then
         echo 1>&2 Usage: $0 source_branch branch_name
         exit 127
fi
 
git push origin $1:$2
git fetch origin
git checkout -b $2 origin/$2
git pull
